# 4.5.8 - https://github.com/minio/operator/blob/v4.5.8/helm/tenant/values.yaml

secrets:
  # MinIO root user and password
  accessKey: minio_root
  secretKey: minio123

## MinIO Tenant Definition
tenant:
  # Tenant name
  name: urbanos-minio
  pools:
    ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
    ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
    ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1
      ## custom name for the pool
      name: pool-0
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 1
      ## size specifies the capacity per volume
      size: 4Gi
      ## storageClass specifies the storage class name to be used for this pool
      storageClassName: azurefile

  ## List of bucket names to create during tenant provisioning
  # https://github.com/minio/operator/issues/1002#issuecomment-1028393926
  buckets:
    - name: "hosted-dataset-files"
    - name: "presto-hive-storage"

  prometheus:
    # When set to true disables the creation of prometheus deployment
    disabled: true

  ## LogSearch API setup for MinIO Tenant.
  log:
    # When set to true disables the creation of logsearch api deployment
    disabled: true

  certificate:
    requestAutoCert: false

ingress:
  api:
    enabled: false
  console:
    enabled: false
