apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crash-custom-ingress
  namespace: urbanos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - crash.URL_W_SUFFIX
      secretName: crash-tls-secret
  rules:
    - host: crash.URL_W_SUFFIX
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mock-cve-data
                port:
                  number: 80
