strimzi-kafka-operator:
  enabled: true
  resources:
    limits:
      memory: 400M
      cpu: 500m
    requests:
      memory: 400M
      cpu: 500m
kafka:
  enabled: true
  storageSize: 4Gi
  version: 3.1.2
  defaultReplicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 700M
    limits:
      cpu: 500m
      memory: 700M
zookeeper:
  resources:
    requests:
      cpu: 200m
      memory: 500M
    limits:
      cpu: 200m
      memory: 500M
kafkaExporter:
  enabled: false
rbac:
  enabled: false
