global:
  require_api_key: true # true since on public endpoints
  redis:
    host: redis-master
    port: 6379
    password: urbanos123
    sslEnabled: false
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  ingress:
    dnsZone: "urbanos-demo.com"
    rootDnsZone: "urbanos-demo.com"
  buckets:
    hostedFileBucket: "hosted-dataset-files"
    hiveStorageBucket: "presto-hive-storage"
  presto:
    url: http://urban-os-trino:8080
  auth:
    auth0_domain: urbanos-demo.us.auth0.com
    jwt_issuer: "https://urbanos-demo.us.auth0.com/" #end "/"" required for jwks_endpoint to be reached
    raptor_url: http://raptor/api
    auth0_management_client_id: jSEXPEDqWSmEs2UGRTvL2cyXKk4BAjtD
  vault:
    endpoint: "urban-os-vault:8200" # not deployed, demo doesn't have vault
  objectStore:
    host: minio
    port: 80
    hiveStoragePath: hive-s3
    accessKey: "minio_root"
    accessSecret: "minio123"
  subdomains:
    andi: "andi"
    share: "sharedata"
    discoveryApi: "data"
    discoveryUi: "discovery"
    raptor: "raptor"

# All images pinned corresponding to chart 1.13.31 (jan 30th 2023)
#     pinned to whatever tag was around that time.
# The urbanos chart should pin versions but it just points to
#     development tags, meaning images could outpace the pinned chart version.
andi:
  enabled: true
  image:
    tag: 2.5.53
  ingress:
    tls: true
    enabled: false
  postgres:
    host: "postgresql"
    port: "5432"
    dbname: "andi"
    user: "urbanos"
    password: "admin"
    verifySNI: false
  auth:
    auth0_client_id: "S3H3cToHVddG7Q7zEKK1nJbzrAy9GqG0"
    # {{ .Release.Name }}-andi-auth0-client-secret will be referenced,
    #   created ahead of time
    auth0_client_secret: ""
  aws:
    accessKeyId: "minio_root"
    accessKeySecret: "minio123"
    s3HostName: "minio"
    s3Port: 80
  s3:
    hostedFileBucket: "andi-public-sample-datasets"
    hostedFileRegion: "us-west-2"
  footer:
    rightLinks: '[{"linkText":"Powered by UrbanOS", "url":"https://github.com/UrbanOS-Public"}]'
  secureCookie: "false"

discovery-api:
  enabled: false
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m
  image:
    tag: development
    pullPolicy: Always
  ingress:
    enabled: true
  secrets:
    discoveryApiPresignKey: "secret-injected-during-deploy"
    guardianSecretKey: "secret-injected-during-deploy"
  postgres:
    host: "postgresql"
    port: "5432"
    dbname: "discovery"
    user: "urbanos"
    password: "admin"
    verifySNI: false
  auth:
    jwks_endpoint: https://urbanos-demo.us.auth0.com/.well-known/jwks.json
    user_info_endpoint: https://urbanos-demo.us.auth0.com/userinfo
    client_id: "3o2V7xHvmV2nQjp1HapX68DzWvxVQdJ2"
    redirect_base_url: "http://localhost"
  elasticsearch:
    host: elasticsearch-master:9200
    tls: false
  aws:
    s3HostName: "minio"
    s3Port: 80

discovery-streams:
  enabled: false
  auth:
    raptor_url: "http://raptor/api"
  resources:
    requests:
      cpu: 500m
      memory: 500M
    limits:
      cpu: 500m
      memory: 500M
  image:
    tag: development
  ingress:
    enabled: true
  kafka:
    dataTopicPrefix: "validated"

discovery-ui:
  enabled: true
  image:
    tag: 2.1.13
  ingress:
    enabled: false
  resources:
    limits:
      memory: 512Mi
      cpu: 400m
    requests:
      memory: 512Mi
      cpu: 400m
  env:
    disc_api_url: "https://data.urbanos-demo.com"
    disc_streams_url: "ws://streams.urbanos-demo.com"
    disc_ui_url: "http://discovery.urbanos-demo.com"
    streets_tile_layer_url: ""
    mapbox_access_token: ""
    auth0_domain: "urbanos-demo.us.auth0.com"
    auth0_client_id: "3o2V7xHvmV2nQjp1HapX68DzWvxVQdJ2"
    auth0_audience: "discovery_api"
    additional_csp_hosts: "*.urbanos-demo.com"
    footer_right_links: '[{"linkText":"Powered by UrbanOS", "url":"https://github.com/UrbanOS-Public"}]'
    regenerate_api_key_ff: true

elasticsearch:
  # https://github.com/elastic/helm-charts/blob/v7.14.0/elasticsearch/values.yaml
  enabled: true
  imageTag: "7.14.1"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  esConfig:
    elasticsearch.yml: |
      ingest.geoip.downloader.enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1500M
    limits:
      cpu: 500m
      memory: 1500M

forklift:
  enabled: false
  overwrite_mode: true
  resources:
    requests:
      cpu: 500m
      memory: 500M
    limits:
      cpu: 500m
      memory: 500M
  image:
    tag: development
  kafka:
    dataTopicPrefix: "validated"
  aws:
    s3HostName: minio
    s3Port: 80

kafka:
  enabled: true
  strimzi-kafka-operator:
    enabled: true
  kafka:
    enabled: true
    storageSize: 4Gi
    version: 3.1.2
    defaultReplicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1000M
      limits:
        cpu: 500m
        memory: 1000M
  zookeeper:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 512Mi
  kafkaExporter:
    enabled: false
  rbac:
    enabled: false

kubernetes-data-platform:
  enabled: false

monitoring:
  enabled: false

# see minio_operator_values.yaml, installed before urbanos helm release
minio-operator:
  enabled: false

# see minio_tenant_values.yaml, installed before urbanos helm release
minio-tenant:
  enabled: false

persistence:
  enabled: true

  metastore:
    postgres:
      host: postgresql
      user: urbanos
      password: admin
      port: 5432
      name: trino_metastore
  resources:
    limits:
      memory: 500M
      cpu: 500m
    requests:
      memory: 500M
      cpu: 500m

  trino:
    image:
      tag: 389
    server:
      workers: 1

    coordinator:
      resources:
        limits:
          memory: 3000M
          cpu: 800m
        requests:
          memory: 3000M
          cpu: 800m

    worker:
      resources:
        limits:
          memory: 3000M
          cpu: 800m
        requests:
          memory: 3000M
          cpu: 800m

    additionalCatalogs:
      hive: |
        connector.name=hive
        hive.metastore.uri=thrift://hive-metastore:8000
        hive.metastore.username=urbanos
        hive.metastore-timeout=1m
        hive.allow-drop-table=true
        hive.allow-rename-table=true
        hive.allow-drop-column=true
        hive.allow-rename-column=true
        hive.allow-add-column=true
        hive.s3.aws-access-key=minio_root
        hive.s3.aws-secret-key=minio123
        hive.s3.path-style-access=true
        hive.s3.endpoint=http://minio:80
        hive.s3.ssl.enabled=false

raptor:
  enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 500M
    limits:
      cpu: 500m
      memory: 500M
  auth:
    auth0_client_id: PuL20cfxgzSu6jpMRQAT2mZ2pwhfFzH8
    auth0_client_secret: "secret-injected-during-deploy"
  image:
    tag: development

reaper:
  enabled: true
  image:
    tag: 2.0.18
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1Gi
      cpu: 300m
      ephemeral-storage: 2G
    requests:
      memory: 1Gi
      cpu: 300m
      ephemeral-storage: 2G

  # Chart Fix: this should instead use global.objectStore
  # Also: does reaper even use s3... ? Region and secrets are set, but host is
  # never referenced, so is it even using minio?
  aws:
    accessKeyId: "minio_root"
    accessKeySecret: "minio123"

valkyrie:
  enabled: false
  image:
    tag: development
  kafka:
    inputTopicPrefix: "transformed"
    outputTopicPrefix: "validated"

alchemist:
  enabled: false
  image:
    tag: development
  kafka:
    inputTopicPrefix: "raw"
    outputTopicPrefix: "transformed"

vault:
  enabled: false

external-services:
  enabled: false
