name: Deploy UrbanOS

on:
  workflow_dispatch:
    inputs:
      entered_kickoff_password:
        description: "Password to start UrbanOS Deployment"
        required: true

jobs:
  Deploy_UrbanOS:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Verify Password
        id: verifypassword
        shell: bash
        run: |
          if [ "$KICKOFF_PASSWORD" == "$ENTERED_KICKOFF_PASSWORD" ]; then
            echo "Password entered correctly"
          else
            echo "Incorrect password entered"
            exit 1
          fi
        env:
          KICKOFF_PASSWORD: ${{secrets.KICKOFF_PASSWORD}}
          ENTERED_KICKOFF_PASSWORD: ${{github.event.inputs.entered_kickoff_password}}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.19.0

      - run: npm ci

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK and Deploy UrbanOS
        uses: hashicorp/terraform-cdk-action@v0.1.13
        with:
          terraformVersion: 1.3.7
          cdktfVersion: 0.15.5
          stackName: juno
          mode: auto-approve-apply
          commentOnPr: false
        env:
          # ensure edits to these are added to the "teardown_urbanos" workflow as well
          JUNO_DEMO_MODE_ENABLED: ${{vars.JUNO_DEMO_MODE_ENABLED}}
          JUNO_RESOURCE_PREFIX: ${{vars.JUNO_RESOURCE_PREFIX}}
          JUNO_AZURE_SUB_ID: ${{secrets.JUNO_AZURE_SUB_ID}}
          JUNO_DEMO_AZURE_APP_ID: ${{secrets.JUNO_DEMO_AZURE_APP_ID}}
          JUNO_DEMO_AZURE_PASSWORD: ${{secrets.JUNO_DEMO_AZURE_PASSWORD}}
          JUNO_DEMO_AZURE_TENANT: ${{secrets.JUNO_DEMO_AZURE_TENANT}}
          JUNO_DEMO_TF_BACKEND_KEY: ${{secrets.JUNO_DEMO_TF_BACKEND_KEY}}
          JUNO_DOMAIN_NO_SUFFIX: ${{secrets.JUNO_DOMAIN_NO_SUFFIX}}
          JUNO_DOMAIN_WITH_SUFFIX: ${{secrets.JUNO_DOMAIN_WITH_SUFFIX}}
          JUNO_ANDI_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_ANDI_AUTH0_CLIENT_SECRET}}
          JUNO_RAPTOR_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_RAPTOR_AUTH0_CLIENT_SECRET}}
