name: Deploy UrbanOS

on:
  workflow_dispatch:
    inputs:
      skip-andi-init:
        type: boolean
        description: Skip initializing andi. Useful to enable this if Andi has already been initialized, and you'd only like to apply the terraform.

jobs:
  Deploy_UrbanOS:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.19.0

      - run: npm ci

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK and to generate Terraform
        uses: hashicorp/terraform-cdk-action@v0.1.13
        with:
          terraformVersion: 1.3.7
          cdktfVersion: 0.15.5
          stackName: juno
          mode: synth-only
          commentOnPr: false
        env:
          # ensure edits to these are added to the "teardown_urbanos" workflow as well
          JUNO_DEMO_MODE_ENABLED: ${{vars.JUNO_DEMO_MODE_ENABLED}}
          JUNO_RESOURCE_PREFIX: ${{vars.JUNO_RESOURCE_PREFIX}}
          # in order of env secrets of github action settings
          AUTH0_USER_API_KEY: ${{secrets.AUTH0_USER_API_KEY}}
          JUNO_ANDI_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_ANDI_AUTH0_CLIENT_SECRET}}
          JUNO_AZURE_SUB_ID: ${{secrets.JUNO_AZURE_SUB_ID}}
          JUNO_DEMO_AZURE_APP_ID: ${{secrets.JUNO_DEMO_AZURE_APP_ID}}
          JUNO_DEMO_AZURE_PASSWORD: ${{secrets.JUNO_DEMO_AZURE_PASSWORD}}
          JUNO_DEMO_AZURE_TENANT: ${{secrets.JUNO_DEMO_AZURE_TENANT}}
          JUNO_DEMO_TF_BACKEND_KEY: ${{secrets.JUNO_DEMO_TF_BACKEND_KEY}}
          JUNO_DOMAIN_NO_SUFFIX: ${{secrets.JUNO_DOMAIN_NO_SUFFIX}}
          JUNO_DOMAIN_WITH_SUFFIX: ${{secrets.JUNO_DOMAIN_WITH_SUFFIX}}
          JUNO_EVENT_HUB_URL: ${{secrets.JUNO_EVENT_HUB_URL}}
          JUNO_RAPTOR_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_RAPTOR_AUTH0_CLIENT_SECRET}}

      - name: Deploy UrbanOS using generated terraform
        run: cd cdktf.out/stacks/juno && terraform apply -refresh=false

      - name: Initialize Andi Sample Datasets
        if: ${{ github.event.inputs.skip-andi-init != 'true' }}
        run: ./scripts/initialize_andi_req_data/initialize_andi.sh
