name: Teardown UrbanOS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment used to deploy urbanos.
        options:
          - dev1
          - qual
          - demo
          - dock
        required: true

jobs:
  Teardown_UrbanOS:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-urbanos.com
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.19.0

      - run: npm ci

      - name: Generate module and provider bindings
        run: npx cdktf-cli@0.15.5 get

      - name: Prepare Teardown with Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.13
        with:
          terraformVersion: 1.3.7
          cdktfVersion: 0.15.5
          stackName: juno
          mode: auto-approve-destroy
          commentOnPr: false
        env:
          # ensure edits to these are added to the "deploy_urbanos" workflow as well
          # in order of .env file secrets and of github action secrets list
          ENV: ${{ github.event.inputs.environment }}
          AUTH0_USER_API_KEY: ${{secrets.AUTH0_USER_API_KEY}}
          JUNO_ANDI_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_ANDI_AUTH0_CLIENT_SECRET}}
          JUNO_AZURE_SUB_ID: ${{secrets.JUNO_AZURE_SUB_ID}}
          JUNO_DEMO_AZURE_APP_ID: ${{secrets.JUNO_DEMO_AZURE_APP_ID}}
          JUNO_DEMO_AZURE_PASSWORD: ${{secrets.JUNO_DEMO_AZURE_PASSWORD}}
          JUNO_DEMO_AZURE_TENANT: ${{secrets.JUNO_DEMO_AZURE_TENANT}}
          JUNO_DEMO_TF_BACKEND_KEY: ${{secrets.JUNO_DEMO_TF_BACKEND_KEY}}
          JUNO_DEMO_TF_ORGANIZATION_NAME: ${{secrets.JUNO_DEMO_TF_ORGANIZATION_NAME}}
          JUNO_DEMO_TF_WORKSPACE_NAME: ${{secrets.JUNO_DEMO_TF_WORKSPACE_NAME}}
          JUNO_DOMAIN_NO_SUFFIX: ${{secrets.JUNO_DOMAIN_NO_SUFFIX}}
          JUNO_DOMAIN_WITH_SUFFIX: ${{secrets.JUNO_DOMAIN_WITH_SUFFIX}}
          JUNO_EVENT_HUB_URL: ${{secrets.JUNO_EVENT_HUB_URL}}
          JUNO_RAPTOR_AUTH0_CLIENT_SECRET: ${{secrets.JUNO_RAPTOR_AUTH0_CLIENT_SECRET}}
          JUNO_RESOURCE_PREFIX: ${{secrets.JUNO_RESOURCE_PREFIX}}
          JUNO_USE_STAGING_LETS_ENCRYPT: does_not_matter
          JUNO_ENABLE_SAURON: does_not_matter
          JUNO_SAURON_GITHUB_PAT: ${{secrets.JUNO_SAURON_GITHUB_PAT}}
